// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArxoixC83HN9Xmdb6FGLbEwo8uO_fReic',
    appId: '1:933179498036:web:5598bf4f2d3a01e8017461',
    messagingSenderId: '933179498036',
    projectId: 'chat-project-1b800',
    authDomain: 'chat-project-1b800.firebaseapp.com',
    databaseURL: 'https://chat-project-1b800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-project-1b800.firebasestorage.app',
    measurementId: 'G-BD8QBVYSR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF73AKRfpSTX-oXzB0RLNY9HRDLJltRD8',
    appId: '1:933179498036:android:e20d933697253b14017461',
    messagingSenderId: '933179498036',
    projectId: 'chat-project-1b800',
    databaseURL: 'https://chat-project-1b800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-project-1b800.firebasestorage.app',
  );

}